### ISSUE TITLE
Stealing Entire Concept

### ISSUE THREAD

**Issue by SmushyTaco** [Level3Studios/ChameleonSupport#1]
I am a former Leviation member and the team created the concept of Chameleon, the name, the icon, the idea of it's functionality and without even asking you steal all that and make something that was supposed to be free and open source paid and closed source

**Comment by SmushyTaco** [comment]
I wouldn't have had a problem with this if you at least asked us but you didn't. You even copied the icon and everything.

**Comment by SmushyTaco** [comment]
Contact me on Twitter @SmushyT or reply here.

**Comment by SalAldana** [comment]
Hello @SmushyRepo not sure what project you are referring to but I didn't copy anything from anyone. I had this idea for this app back in December (my first commit for this project was December 14, 2018). If you can provide any links to this project that you and your team was working on I can let you know for a fact whether I had seen/viewed anything you did.

**Comment by SmushyTaco** [comment]
![ee34f445-4d33-4ba3-8e7f-e9f77c51d32d](https://user-images.githubusercontent.com/41648290/53139522-b7d5d700-353e-11e9-8d77-c4a4cffb30d9.jpeg)
![a777db9f-9de2-4aa5-a69f-6991988c5195](https://user-images.githubusercontent.com/41648290/53139523-b86e6d80-353e-11e9-9a73-3eea97ad832c.jpeg)
Not going to attack you legally or anything it's cool that you made what the old team I was in couldn't but it would have been nice if you just asked us.

**Comment by SalAldana** [comment]
@SmushyRepo , I’m going to go ahead an close this since you didn’t really provide anything that can lead to me “stealing” something from your former team. All you showed was a private repo, which I would never have access to so not sure how I could have taken anything from it. So yeah, just a coincidence with the name and functionality so no need to ask permission from a group I never heard of.
